### curl command to test the CreateOrder remove the comments before running the cURL command in the terminal or Postman

# curl --location 'http://localhost:8000/order'
#--header 'Content-Type: application/json'
#--data '{
#  "name":"FUSCA AZUL",
#  "price": 101945.90,
#  "tax": 2.5
#}
#'
POST http://localhost:8000/order
Content-Type: application/json

{
  "name": "FUSCA AZUL",
  "price": 101945.90,
  "tax": 2.5
}


### curl command to test the GetOrder remove the comments before running the cURL command in the terminal or Postman
# curl --location 'http://localhost:8000/orders'
GET http://localhost:8000/orders

###