### curl command to test the CreateOrder remove the comments before running the cURL command in the terminal or Postman

# curl --location 'http://localhost:8000/order'
#--header 'Content-Type: application/json'
#--data '{
#  "name":"TV 50",
#  "price": 4990.90,
#  "tax": 0.5
#}
#'
POST http://localhost:8000/order
Content-Type: application/json

{
  "name": "TV 50",
  "price": 4990.90,
  "tax": 0.5
}


###

